In [80]:
import numpy as np
import cv2
import face_recognition
import os
import glob
import random
import time
import sys, getopt

dirname, filename = os.path.split(os.path.abspath('/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/whatMemeAmI.py'))

locationFolder = 'memes/'

data = []
dataPeopleEdges = [0]
dataPeopleImages = []
maxPeople = 3

for i in np.arange(1, maxPeople+1):
    dir_path = os.path.join(dirname+'/'+locationFolder+str(i)+'/','*g')
    files_in_dir_path = glob.glob(dir_path)
    
    dataPeopleEdges.append(dataPeopleEdges[-1]+int(len(files_in_dir_path)))
    dataPeopleImages.append(int(len(files_in_dir_path)/i))
    
    for fil in sorted(files_in_dir_path):
        print(fil)
        img_original = cv2.imread(fil)
        img = cv2.resize(img_original, (1, 1))
        data.append(img)

/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/changeMyMind.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/girlHouseOnFire.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/hideThePainHarold.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/keyAndPeel.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/leonardoDiCaprio.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/mockingSpongebob.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/monkey.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/oldLadyAtComputer.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/oneDoesNotSimply.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/skeleton.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/spongegar.png
/Users/DidierRodriguesLopes/Documents/git/WhatMemeAmI/memes/1/twoButtons.png
/Users/DidierRodriguesLopes/Documents/git/Wh

In [78]:
dataPeopleImages

[12, 2, 2]

In [63]:
len(glob.glob('/Users/DidierRodriguesLopes/Documents/git//WhatMemeAmI/memes/1/*g'))

12

In [5]:
dataPeopleEdges = [0, 12, 16, 22]
dataPeopleImages = [12, 2, 2]

import numpy as np
array = np.arange(22)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [40]:
faceLocations = [1, 2, 3]
numFaces = len(faceLocations)
#dataPeopleEdges[numFaces-1] + np.random.permutation(numFaces*dataPeopleImages[numFaces-1])

#np.random.permutation(dataPeopleEdges[numFaces-1]:numFaces:dataPeopleEdges[numFaces])

In [44]:
np.random.permutation(np.arange(dataPeopleEdges[numFaces-1], dataPeopleEdges[numFaces], numFaces))

array([16, 19])

In [28]:
dataPeopleEdges[numFaces-1]

12

In [29]:
dataPeopleEdges[numFaces]

16

In [30]:
numFaces

2

In [33]:
np.arange(12, 16, 2)

array([12, 14])